# Deployment Template
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: login
  namespace: dev
spec:
  # 1 Pod should exist at all times.
  replicas: 1
  selector:
    matchLabels:
      app: login
  template:
    metadata:
      labels:
        app: login
    spec:
      containers:
      - name: login
        image: ravi2krishna/login-2424
        ports:
        - containerPort: 80