# Pod Manifest File For Multi Container
# This will pass, as we go with two differnt images which use differnt ports
apiVersion: v1
kind: Pod
metadata:
  name: multi-pod
spec:
  containers:
  - name: c1
    image: nginx
    ports:
    - containerPort: 80 
  - name: c2
    image: ravi2krishna/nodejs-api
    ports:
    - containerPort: 8080 